### ISSUE TITLE
Validate: Message for incorrect inputField property unclear

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#35]
I had `help_text` instead of `helpText` and got:

![](https://cdn.zapier.com/storage/photos/ace25cf77d8dc944baf52ec08d7ac26d.png)

This suggests that the value of `App.creates.fork_array.operation.inputFields` is incorrect, while it is `App.creates.fork_array.operation.inputFields[0].help_text` that is incorrect.

**Comment by BrunoBernardino** [comment]
This had some improvements as part of https://github.com/zapier/zapier-platform-schema/pull/24 but didn't _really_ get fixed in a super clearer way.

**Comment by FokkeZB** [comment]
As in.. the error is still the same 😉 

![](https://cdn.zapier.com/storage/photos/cc0075d30e790f75fd7fcc070c7ff348.png)

**Comment by BrunoBernardino** [comment]
I personally think `</FieldSchema>` is clearer than `[subschema 0]`, but the overall message isn't clear and this will definitely need some "human language conversion" from those `jsonschema` errors.

**Comment by FokkeZB** [comment]
Ah, sorry.. totally missed that. Yes, that's definitely more helpful. I guess to fix this we'd need to change how we validate if an object meets its schema and if it doesn't show why it doesn't?

**Comment by xavdid** [comment]
we've got better validation now, so this is fixed
